### ISSUE TITLE
possibility of etymology support

### ISSUE THREAD

**Issue by Pintliz** [ninja33/ODH#114]
some of the dictionary used provides the etymology of the searched word, is it possible to put these into {{extrainfo}} or a new etymology field?
for me personally this would make remembering the word a lot easier.

collins
![image](https://user-images.githubusercontent.com/24824399/65059735-109b1000-d966-11e9-82a8-0667ea765eb5.png)

google define+word (sourced from oxford)
![image](https://user-images.githubusercontent.com/24824399/65059911-62439a80-d966-11e9-9a71-84171d9fc434.png)

**Comment by ninja33** [comment]
Yes, It can be done by customizing dictionary script.

first off, you need change dictionary area in collins web site. because collins COBUILD dictioary does not contain etymology field.
![image](https://user-images.githubusercontent.com/20181220/65156913-74a2fe80-da62-11e9-97e7-74a09a90a075.png)

second, under that section, you can see, all etymology content is under a div called 'div content etyms'
![image](https://user-images.githubusercontent.com/20181220/65157159-dfecd080-da62-11e9-82f8-5ce2248d82ed.png)

so ,all you need is to assign this div content to {{extra info}} field.
