### ISSUE TITLE
No dictionary in settings

### ISSUE THREAD

**Issue by skygate2012** [ninja33/ODH#59]
I ported this addon using [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) to Firefox, but there's no dictionary found in the dropdown list. How can I debug this issue?
![firefox_2018-12-16_10-39-58](https://user-images.githubusercontent.com/7148976/50051786-90841780-0153-11e9-817c-d23bbbc3f0ef.png)

**Comment by ninja33** [comment]
Well, actually you can’t simply port it to Firefox, because the sandbox machnism used in Chrome extension currently is not support by Firefox. 

All dictionaries listed in Chrome extension- ODH currently is loaded by dynamically evaluated javascript code. For sucerity purpose, these “eval”-ed code is running within sandbox environment.  That’s why your code is not running successfully. 

You have to manually convert such code if you unstand the source.

**Comment by skygate2012** [comment]
> 
> 
> Well, actually you can’t simply port it to Firefox, because the sandbox machnism used in Chrome extension currently is not support by Firefox.
> 
> All dictionaries listed in Chrome extension- ODH currently is loaded by dynamically evaluated javascript code. For sucerity purpose, these “eval”-ed code is running within sandbox environment. That’s why your code is not running successfully.
> 
> You have to manually convert such code if you unstand the source.

The previous edition (anki-dict-helper) of this addon works perfectly in Firefox, can you guide me how to get back to the old method?
The reason I decide switch to this newer edition is because the dictionary the old addon provided is too limited in vocabulary size. Maybe there is a way to replace the dictionary of the old addon with the newer one?

**Comment by skygate2012** [comment]
Closing this issue now as the author has released [the Firefox version](https://addons.mozilla.org/en-US/firefox/addon/online-dictionary-helper/), much appreciated for your efforts! @ninja33
